# Generated by Django 5.0.6 on 2024-10-13 05:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menfess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=255)),
                ('to_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_reply_name', models.CharField(max_length=255)),
                ('reply_message', models.TextField()),
                ('reply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('menfess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menfess_app.menfess')),
            ],
        ),
    ]
