# Generated by Django 5.0.6 on 2024-10-13 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menfess_app', '0002_alter_menfess_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menfess',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 10, 47, 12, 27055, tzinfo=datetime.timezone.utc)),
        ),
    ]
