# Generated by Django 5.0.6 on 2024-10-14 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menfess_app', '0003_alter_menfess_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menfess',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 3, 53, 26, 634770, tzinfo=datetime.timezone.utc)),
        ),
    ]
