# Generated by Django 5.0.6 on 2024-10-19 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menfess_app', '0004_alter_menfess_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menfess',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 3, 50, 28, 544337, tzinfo=datetime.timezone.utc)),
        ),
    ]
